#----------web container---------
server:
  port: 8080
  servlet:
    context-path: /yjytke
#--------spring--------
spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://127.0.0.1:3306/yjytke?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  #-------------mvc--------------
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#---------------mybatis--------------
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  
#---------------pagehelper-------------- 
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql